import { ArrowLeft, Bookmark, BookmarkCheck, CheckCircle2, CircleX, ExternalLink, ShieldAlert, Target, TriangleAlert } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { DataBadge } from '../components/DataBadge';
import { Metric } from '../components/Metric';
import { PriceChart } from '../components/PriceChart';
import { RiskGradeBadge, ScoreGauge } from '../components/ScoreGauge';
import { useRadar } from '../context/RadarContext';
import type { MarketAsset } from '../types/market';
import { dateTime, money, number, percent } from '../utils/format';
import { EmptyState } from '../components/States';
import { memeRiskLabel } from '../utils/risk';

export function AssetDetailPage() {
  const { id } = useParams();
  const { assets, isWatched, toggleWatchlist } = useRadar();
  const asset = assets.find((item) => item.id === id);
  if (!asset) return <EmptyState title="Asset not found" message="The generated dataset does not contain this asset." />;
  const watched = isWatched(asset.id);
  return (
    <>
      <Link to={asset.kind === 'stock' ? '/stocks' : asset.kind === 'crypto' ? '/crypto' : '/memes'} className="mb-5 inline-flex items-center gap-2 text-sm text-muted hover:text-white"><ArrowLeft className="h-4 w-4"/> Back to screener</Link>
      <header className="mb-6 rounded-3xl border border-line bg-panel p-5 sm:p-7">
        <div className="flex flex-wrap items-start justify-between gap-6"><div><div className="mb-3 flex items-center gap-2"><DataBadge asset={asset}/>{asset.kind === 'meme' && <span className="rounded-full bg-loss/10 px-2 py-1 text-[10px] font-bold uppercase text-loss">{memeRiskLabel(asset.score.risk, asset.dataQuality)}</span>}</div><h1 className="text-3xl font-black tracking-tight sm:text-5xl">{asset.symbol} <span className="text-muted">/ {asset.name}</span></h1><p className="mt-3 text-sm text-muted">{asset.category} · {asset.exchange} · Updated {dateTime(asset.dataTimestamp)}</p></div><button onClick={() => toggleWatchlist(asset.id)} className="button-secondary">{watched ? <BookmarkCheck className="h-4 w-4 text-gain"/> : <Bookmark className="h-4 w-4"/>}{watched ? 'Watched' : 'Add to watchlist'}</button></div>
        <div className="mt-8 grid gap-6 md:grid-cols-[1fr_auto_auto] md:items-end"><div><p className="text-4xl font-black">{money(asset.price)}</p><p className={`mt-1 font-semibold ${(asset.change24h ?? 0) >= 0 ? 'text-gain' : 'text-loss'}`}>{percent(asset.change24h)} {asset.kind === 'stock' ? 'daily' : '24h'}</p></div><ScoreGauge value={asset.score.opportunity}/><RiskGradeBadge grade={asset.score.riskGrade} risk={asset.score.risk}/></div>
      </header>
      {asset.warnings.length > 0 && <section className="mb-6 rounded-2xl border border-loss/20 bg-loss/5 p-4"><h2 className="mb-2 flex items-center gap-2 font-bold text-loss"><TriangleAlert className="h-5 w-5"/>Warnings</h2><ul className="space-y-1 text-sm text-red-100">{asset.warnings.map((warning) => <li key={warning}>• {warning}</li>)}</ul></section>}
      <div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
        <section className="card"><h2 className="section-title">Price history</h2><PriceChart data={asset.priceHistory}/><p className="mt-2 text-xs text-muted">{asset.isDemo ? 'Illustrative demo series; not historical market data.' : `Raw source: ${asset.sourceLabel}.`}</p></section>
        <section className="card"><h2 className="section-title">Important metrics</h2><div className="grid grid-cols-2 gap-x-5 gap-y-6 sm:grid-cols-3 xl:grid-cols-2">{detailMetrics(asset).map((metric) => <Metric key={metric.label} {...metric}/>)}</div></section>
      </div>
      <section className="card mt-6"><div className="mb-5"><h2 className="section-title">Transparent score breakdown</h2><p className="text-sm text-muted">Raw metrics feed normalized sub-scores. Weighting is visible; penalties are separate.</p></div><div className="space-y-4">{asset.score.parts.map((part) => <div key={part.label} className="grid gap-2 sm:grid-cols-[180px_1fr_70px]"><div><p className="text-sm font-semibold">{part.label}</p><p className="text-xs text-muted">{Math.round(part.weight * 100)}% weight</p></div><div className="h-2 self-center overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-gain" style={{ width: `${part.score}%` }}/></div><p className="text-right text-sm font-bold">{part.score}/100</p><p className="text-xs text-muted sm:col-start-2 sm:col-span-2">{part.explanation}</p></div>)}</div>{asset.score.penalties.length > 0 && <div className="mt-6 border-t border-line pt-5"><h3 className="mb-3 font-bold text-loss">Separate penalties</h3>{asset.score.penalties.map((penalty) => <div className="mb-2 flex justify-between gap-4 text-sm" key={penalty.label}><span>{penalty.label}: <span className="text-muted">{penalty.explanation}</span></span><strong className="text-loss">−{penalty.points}</strong></div>)}</div>}<p className="mt-5 rounded-xl bg-black/20 p-3 text-xs text-muted">{asset.score.explanation}</p></section>
      <div className="mt-6 grid gap-6 lg:grid-cols-2"><ThesisCard title="Bull case" icon={CheckCircle2} tone="gain" text={asset.bullCase} items={asset.catalysts}/><ThesisCard title="Bear case" icon={CircleX} tone="loss" text={asset.bearCase} items={asset.risks}/></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-3"><ListCard title="What must happen for the thesis to work?" icon={Target} items={asset.thesisNeeds}/><ListCard title="Thesis invalidation points" icon={CircleX} items={asset.invalidationPoints}/><ListCard title="What could cause permanent loss?" icon={ShieldAlert} items={asset.permanentLossCauses}/></div>
      <section className="card mt-6"><h2 className="section-title">Scenario analysis — no unsupported price targets</h2><div className="grid gap-4 md:grid-cols-3">{asset.scenarios.map((scenario) => <article key={scenario.label} className="rounded-xl border border-line bg-black/20 p-4"><h3 className="font-bold">{scenario.label}</h3><p className="my-3 text-sm leading-6 text-muted">{scenario.narrative}</p><p className="text-[10px] uppercase tracking-wider text-muted">Required assumptions</p><ul className="mt-2 space-y-1 text-xs">{scenario.assumptions.map((assumption) => <li key={assumption}>• {assumption}</li>)}</ul></article>)}</div></section>
      <section className="card mt-6"><h2 className="section-title">Sources and data integrity</h2><div className="grid gap-4 text-sm sm:grid-cols-2"><div><p className="label">Raw source</p><p>{asset.sourceLabel}</p></div><div><p className="label">Retrieval time</p><p>{dateTime(asset.dataTimestamp)}</p></div><div><p className="label">Data quality</p><p className="capitalize">{asset.dataQuality}{asset.stale ? ' · stale' : ''}</p></div><div><p className="label">Calculated fields</p><p>Opportunity, risk, momentum, relative metrics, and scenario classifications.</p></div></div>{asset.sourceLinks.length || (asset.kind === 'stock' && asset.recentFilings.length) ? <div className="mt-5 flex flex-wrap gap-3">{[...asset.sourceLinks, ...(asset.kind === 'stock' ? asset.recentFilings : [])].map((source) => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="button-secondary">{source.name}<ExternalLink className="h-3.5 w-3.5"/></a>)}</div> : <p className="mt-5 text-sm text-muted">Relevant filings or source links: Data unavailable in this dataset. No link has been invented.</p>}</section>
    </>
  );
}

function detailMetrics(asset: MarketAsset): Array<{label: string; value: string; help?: string}> {
  const base = [{ label: 'Market capitalization', value: money(asset.marketCap, true) }, { label: 'Trading volume', value: money(asset.volume24h, true) }];
  if (asset.kind === 'stock') return [...base, { label: 'Enterprise value', value: money(asset.enterpriseValue, true) }, { label: 'Revenue growth', value: percent(asset.revenueGrowth) }, { label: 'Free cash flow', value: money(asset.freeCashFlow, true) }, { label: 'Cash / debt', value: `${money(asset.cash, true)} / ${money(asset.debt, true)}` }, { label: 'Price to sales', value: number(asset.priceToSales) }, { label: 'P/E', value: number(asset.priceToEarnings) }, { label: 'Short interest', value: percent(asset.shortInterest) }, { label: 'Days to cover', value: number(asset.daysToCover) }, { label: 'Relative volume', value: asset.relativeVolume === null ? 'Data unavailable' : `${asset.relativeVolume.toFixed(1)}×` }, { label: 'Dilution risk', value: asset.dilutionRisk.toUpperCase() }];
  if (asset.kind === 'crypto') return [...base, { label: 'Market cap rank', value: number(asset.marketCapRank) }, { label: 'Circulating supply', value: number(asset.circulatingSupply, true) }, { label: 'Total supply', value: number(asset.totalSupply, true) }, { label: 'ATH drawdown', value: percent(asset.athDrawdown) }, { label: 'Active addresses', value: number(asset.activeAddresses, true) }, { label: 'Protocol revenue', value: money(asset.protocolRevenue, true) }, { label: 'TVL', value: money(asset.totalValueLocked, true) }, { label: 'Regulatory risk', value: asset.regulatoryRisk.toUpperCase() }];
  return [...base, { label: 'Chain', value: asset.chain }, { label: 'FDV', value: money(asset.fullyDilutedValuation, true) }, { label: 'Liquidity', value: money(asset.liquidity, true) }, { label: 'Volume / liquidity', value: number(asset.volumeToLiquidity) }, { label: 'Holders', value: number(asset.holders, true) }, { label: 'Top-10 concentration', value: percent(asset.top10Concentration) }, { label: 'Contract verified', value: asset.contractVerified === null ? 'Data unavailable' : asset.contractVerified ? 'Yes' : 'No' }, { label: 'Liquidity locked', value: asset.liquidityLocked === null ? 'Data unavailable' : asset.liquidityLocked ? 'Yes' : 'No' }, { label: 'Mint authority', value: asset.mintAuthority === null ? 'Data unavailable' : asset.mintAuthority ? 'Present' : 'Disabled' }];
}

function ThesisCard({ title, icon: Icon, tone, text, items }: { title: string; icon: typeof CheckCircle2; tone: 'gain' | 'loss'; text: string; items: string[] }) { return <section className="card"><h2 className={`section-title flex items-center gap-2 ${tone === 'gain' ? 'text-gain' : 'text-loss'}`}><Icon className="h-5 w-5"/>{title}</h2><p className="mb-4 text-sm leading-6 text-muted">{text}</p><ul className="space-y-2 text-sm">{items.map((item) => <li key={item}>• {item}</li>)}</ul></section>; }
function ListCard({ title, icon: Icon, items }: { title: string; icon: typeof Target; items: string[] }) { return <section className="card"><h2 className="mb-4 flex items-center gap-2 font-bold"><Icon className="h-5 w-5 text-gain"/>{title}</h2><ul className="space-y-3 text-sm text-muted">{items.map((item) => <li key={item}>• {item}</li>)}</ul></section>; }
